-- ============================================================
-- Migration 046: Telemarketing permissions seeding
--
-- Adds the 7 canonical telemarketing permission keys required to
-- guard all telemarketing endpoints (Phase TM-1 hardening).
--
-- PERMISSION MATRIX (scope_type = BRANCH unless noted)
-- -------------------------------------------------------
-- Role                        | targets | lists | lists  | calls  | appts  | calls      | appts
--                             | .view   | .view | .gen   | .create| .create| .view_hist | .view
-- ADMIN                       |    ✓    |   ✓   |   ✓    |   ✓    |   ✓    |     ✓      |   ✓
-- BRANCH_MANAGER              |    ✓    |   ✓   |   ✓    |   ✗    |   ✗    |     ✓      |   ✓
-- TELEMARKETER                |    ✗    |   ✓   |   ✗    |   ✓    |   ✓    |     ✓      |   ✓
-- CUSTOMER_SERVICE_SUPERVISOR |    ✓    |   ✓   |   ✗    |   ✓    |   ✓    |     ✓      |   ✓
-- SYSTEM_ADMIN                |    ✓    |   ✓   |   ✓    |   ✓    |   ✓    |     ✓      |   ✓  (GLOBAL)
--
-- Notes:
--   • TELEMARKETER does not get targets.view or lists.generate — the plan
--     is generated by the branch manager or supervisor, not the caller.
--   • CUSTOMER_SERVICE_SUPERVISOR does not get lists.generate — she works
--     within her assigned scope; list generation is a manager action.
--   • Scope type is BRANCH for all operational roles.
--     User/team scope filtering is deferred to a later migration.
--   • Idempotent: safe to run multiple times on any environment.
-- ============================================================

-- ── Step 1: Insert permission keys ───────────────────────────────────────────

INSERT INTO permissions (key, module, sub_module, action, display_name, display_order)
VALUES
  ('telemarketing.targets.view',       'telemarketing', 'targets',      'view',         'عرض أهداف التيلماركتر',        160),
  ('telemarketing.lists.view',         'telemarketing', 'lists',        'view',         'عرض قوائم الاتصال',             161),
  ('telemarketing.lists.generate',     'telemarketing', 'lists',        'generate',     'توليد قائمة الاتصال اليومية',  162),
  ('telemarketing.calls.create',       'telemarketing', 'calls',        'create',       'تسجيل نتيجة اتصال',            163),
  ('telemarketing.appointments.create','telemarketing', 'appointments', 'create',       'حجز موعد زيارة تسويقية',       164),
  ('telemarketing.calls.view_history', 'telemarketing', 'calls',        'view_history', 'عرض سجل الاتصالات',            165),
  ('telemarketing.appointments.view',  'telemarketing', 'appointments', 'view',         'عرض مواعيد التيلماركتر',       166)
ON CONFLICT (key) DO UPDATE
  SET module       = EXCLUDED.module,
      sub_module   = EXCLUDED.sub_module,
      action       = EXCLUDED.action,
      display_name = EXCLUDED.display_name,
      display_order= EXCLUDED.display_order;


-- ── Step 2: SYSTEM_ADMIN — full access (GLOBAL) ───────────────────────────────

INSERT INTO role_permission_grants (role_id, permission_id, scope_type)
SELECT r.id, p.id, 'GLOBAL'
  FROM roles r
  JOIN permissions p ON p.key IN (
    'telemarketing.targets.view',
    'telemarketing.lists.view',
    'telemarketing.lists.generate',
    'telemarketing.calls.create',
    'telemarketing.appointments.create',
    'telemarketing.calls.view_history',
    'telemarketing.appointments.view'
  )
 WHERE r.name        = 'SYSTEM_ADMIN'
   AND r.is_template = TRUE
   AND r.branch_id   IS NULL
ON CONFLICT (role_id, permission_id) DO UPDATE
  SET scope_type = EXCLUDED.scope_type,
      updated_at = NOW();

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
  FROM roles r
  JOIN permissions p ON p.key IN (
    'telemarketing.targets.view',
    'telemarketing.lists.view',
    'telemarketing.lists.generate',
    'telemarketing.calls.create',
    'telemarketing.appointments.create',
    'telemarketing.calls.view_history',
    'telemarketing.appointments.view'
  )
 WHERE r.name        = 'SYSTEM_ADMIN'
   AND r.is_template = TRUE
   AND r.branch_id   IS NULL
ON CONFLICT (role_id, permission_id) DO NOTHING;


-- ── Step 3: ADMIN — full access (BRANCH) ──────────────────────────────────────

INSERT INTO role_permission_grants (role_id, permission_id, scope_type)
SELECT r.id, p.id, 'BRANCH'
  FROM roles r
  JOIN permissions p ON p.key IN (
    'telemarketing.targets.view',
    'telemarketing.lists.view',
    'telemarketing.lists.generate',
    'telemarketing.calls.create',
    'telemarketing.appointments.create',
    'telemarketing.calls.view_history',
    'telemarketing.appointments.view'
  )
 WHERE r.name        = 'ADMIN'
   AND r.is_template = TRUE
   AND r.branch_id   IS NULL
ON CONFLICT (role_id, permission_id) DO UPDATE
  SET scope_type = EXCLUDED.scope_type,
      updated_at = NOW();

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
  FROM roles r
  JOIN permissions p ON p.key IN (
    'telemarketing.targets.view',
    'telemarketing.lists.view',
    'telemarketing.lists.generate',
    'telemarketing.calls.create',
    'telemarketing.appointments.create',
    'telemarketing.calls.view_history',
    'telemarketing.appointments.view'
  )
 WHERE r.name        = 'ADMIN'
   AND r.is_template = TRUE
   AND r.branch_id   IS NULL
ON CONFLICT (role_id, permission_id) DO NOTHING;


-- ── Step 4: BRANCH_MANAGER — view + generate, no execution (BRANCH) ──────────

INSERT INTO role_permission_grants (role_id, permission_id, scope_type)
SELECT r.id, p.id, 'BRANCH'
  FROM roles r
  JOIN permissions p ON p.key IN (
    'telemarketing.targets.view',
    'telemarketing.lists.view',
    'telemarketing.lists.generate',
    'telemarketing.calls.view_history',
    'telemarketing.appointments.view'
  )
 WHERE r.name        = 'BRANCH_MANAGER'
   AND r.is_template = TRUE
   AND r.branch_id   IS NULL
ON CONFLICT (role_id, permission_id) DO UPDATE
  SET scope_type = EXCLUDED.scope_type,
      updated_at = NOW();

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
  FROM roles r
  JOIN permissions p ON p.key IN (
    'telemarketing.targets.view',
    'telemarketing.lists.view',
    'telemarketing.lists.generate',
    'telemarketing.calls.view_history',
    'telemarketing.appointments.view'
  )
 WHERE r.name        = 'BRANCH_MANAGER'
   AND r.is_template = TRUE
   AND r.branch_id   IS NULL
ON CONFLICT (role_id, permission_id) DO NOTHING;


-- ── Step 5: TELEMARKETER — caller permissions only (BRANCH) ───────────────────

INSERT INTO role_permission_grants (role_id, permission_id, scope_type)
SELECT r.id, p.id, 'BRANCH'
  FROM roles r
  JOIN permissions p ON p.key IN (
    'telemarketing.lists.view',
    'telemarketing.calls.create',
    'telemarketing.appointments.create',
    'telemarketing.calls.view_history',
    'telemarketing.appointments.view'
  )
 WHERE r.name        = 'TELEMARKETER'
   AND r.is_template = TRUE
   AND r.branch_id   IS NULL
ON CONFLICT (role_id, permission_id) DO UPDATE
  SET scope_type = EXCLUDED.scope_type,
      updated_at = NOW();

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
  FROM roles r
  JOIN permissions p ON p.key IN (
    'telemarketing.lists.view',
    'telemarketing.calls.create',
    'telemarketing.appointments.create',
    'telemarketing.calls.view_history',
    'telemarketing.appointments.view'
  )
 WHERE r.name        = 'TELEMARKETER'
   AND r.is_template = TRUE
   AND r.branch_id   IS NULL
ON CONFLICT (role_id, permission_id) DO NOTHING;


-- ── Step 6: CUSTOMER_SERVICE_SUPERVISOR — supervisor scope (BRANCH) ───────────

INSERT INTO role_permission_grants (role_id, permission_id, scope_type)
SELECT r.id, p.id, 'BRANCH'
  FROM roles r
  JOIN permissions p ON p.key IN (
    'telemarketing.targets.view',
    'telemarketing.lists.view',
    'telemarketing.calls.create',
    'telemarketing.appointments.create',
    'telemarketing.calls.view_history',
    'telemarketing.appointments.view'
  )
 WHERE r.name        = 'CUSTOMER_SERVICE_SUPERVISOR'
   AND r.is_template = TRUE
   AND r.branch_id   IS NULL
ON CONFLICT (role_id, permission_id) DO UPDATE
  SET scope_type = EXCLUDED.scope_type,
      updated_at = NOW();

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
  FROM roles r
  JOIN permissions p ON p.key IN (
    'telemarketing.targets.view',
    'telemarketing.lists.view',
    'telemarketing.calls.create',
    'telemarketing.appointments.create',
    'telemarketing.calls.view_history',
    'telemarketing.appointments.view'
  )
 WHERE r.name        = 'CUSTOMER_SERVICE_SUPERVISOR'
   AND r.is_template = TRUE
   AND r.branch_id   IS NULL
ON CONFLICT (role_id, permission_id) DO NOTHING;


-- ── Verification queries (run manually after applying) ────────────────────────
--
-- SELECT r.name AS role, p.key AS permission, rpg.scope_type
--   FROM role_permission_grants rpg
--   JOIN roles r       ON r.id  = rpg.role_id
--   JOIN permissions p ON p.id  = rpg.permission_id
--  WHERE r.is_template = TRUE
--    AND p.key LIKE 'telemarketing.%'
--  ORDER BY r.name, p.key;
