-- ============================================================
-- Migration 061: Insert real Syrian geographic data
-- Levels: 1=Governorate, 2=Region, 3=Sub-district, 4=Neighborhood
-- ============================================================

-- -----------------------------------------------------------
-- Governorates already exist (ids: 1=دمشق, 2=حلب, 9=اللاذقية, 10=حمص, 11=طرطوس)
-- We insert Regions, Sub-districts, and Neighborhoods below.
-- -----------------------------------------------------------

-- ============================================================
-- 1. REGIONS (المناطق) — level 2
-- ============================================================
INSERT INTO geo_units (name, level, parent_id) VALUES
  -- دمشق (parent_id = 1)
  ('دمشق القديمة', 2, 1),
  ('مرج الصافحة', 2, 1),
  ('جرمانا', 2, 1),
  ('مزة', 2, 1),
  ('دوما', 2, 1),
  ('القطيفة', 2, 1),
  ('المؤتمنة', 2, 1),
  ('داريا', 2, 1),
  -- حلب (parent_id = 2)
  ('حلب القديمة', 2, 2),
  ('الشهباء', 2, 2),
  ('أعزاز', 2, 2),
  ('السفيرة', 2, 2),
  ('باب الفرج', 2, 2),
  ('النيرب', 2, 2),
  ('الأتارب', 2, 2),
  ('الحضر', 2, 2),
  -- اللاذقية (parent_id = 9)
  ('اللاذقية', 2, 9),
  ('جبلة', 2, 9),
  ('القرداحة', 2, 9),
  ('الحفة', 2, 9),
  ('صلانفة', 2, 9),
  -- حمص (parent_id = 10)
  ('حمص القديمة', 2, 10),
  ('الواعر', 2, 10),
  ('المخرم', 2, 10),
  ('القصير', 2, 10),
  ('الرستن', 2, 10),
  ('تالدو', 2, 10),
  ('مصياف', 2, 10),
  ('المشتة', 2, 10),
  -- طرطوس (parent_id = 11)
  ('طرطوس', 2, 11),
  ('بنياس', 2, 11),
  ('الصافية', 2, 11),
  ('الدريكيش', 2, 11),
  ('شيخ بدر', 2, 11)
ON CONFLICT DO NOTHING;

-- ============================================================
-- 2. SUB-DISTRICTS (النواحي) — level 3
-- ============================================================
INSERT INTO geo_units (name, level, parent_id) VALUES
  -- دمشق القديمة regions
  ('الحميدية', 3, (SELECT id FROM geo_units WHERE name = 'دمشق القديمة' AND level = 2)),
  ('الصالحية', 3, (SELECT id FROM geo_units WHERE name = 'دمشق القديمة' AND level = 2)),
  ('المالكي', 3, (SELECT id FROM geo_units WHERE name = 'دمشق القديمة' AND level = 2)),
  ('باب توما', 3, (SELECT id FROM geo_units WHERE name = 'مرج الصافحة' AND level = 2)),
  ('التل', 3, (SELECT id FROM geo_units WHERE name = 'مرج الصافحة' AND level = 2)),
  ('ميزه', 3, (SELECT id FROM geo_units WHERE name = 'مرج الصافحة' AND level = 2)),
  ('جرمانا القديمة', 3, (SELECT id FROM geo_units WHERE name = 'جرمانا' AND level = 2)),
  ('محردة', 3, (SELECT id FROM geo_units WHERE name = 'جرمانا' AND level = 2)),
  ('بيت جند', 3, (SELECT id FROM geo_units WHERE name = 'جرمانا' AND level = 2)),
  ('مزة القديمة', 3, (SELECT id FROM geo_units WHERE name = 'مزة' AND level = 2)),
  ('المعرة', 3, (SELECT id FROM geo_units WHERE name = 'مزة' AND level = 2)),
  ('بيت تمانة', 3, (SELECT id FROM geo_units WHERE name = 'مزة' AND level = 2)),
  ('دوما القديمة', 3, (SELECT id FROM geo_units WHERE name = 'دوما' AND level = 2)),
  ('المعرض', 3, (SELECT id FROM geo_units WHERE name = 'دوما' AND level = 2)),
  ('بيت سادر', 3, (SELECT id FROM geo_units WHERE name = 'دوما' AND level = 2)),
  -- القطيفة regions
  ('القطيفة القديمة', 3, (SELECT id FROM geo_units WHERE name = 'القطيفة' AND level = 2)),
  ('العباسيين', 3, (SELECT id FROM geo_units WHERE name = 'القطيفة' AND level = 2)),
  ('كفر سوسة', 3, (SELECT id FROM geo_units WHERE name = 'القطيفة' AND level = 2)),
  -- المؤتمنة regions
  ('المؤتمنة', 3, (SELECT id FROM geo_units WHERE name = 'المؤتمنة' AND level = 2)),
  ('جبادية', 3, (SELECT id FROM geo_units WHERE name = 'المؤتمنة' AND level = 2)),
  ('الكفر', 3, (SELECT id FROM geo_units WHERE name = 'المؤتمنة' AND level = 2)),
  -- داريا regions
  ('داريا القديمة', 3, (SELECT id FROM geo_units WHERE name = 'داريا' AND level = 2)),
  ('الخليج', 3, (SELECT id FROM geo_units WHERE name = 'داريا' AND level = 2)),
  ('بيت حجار', 3, (SELECT id FROM geo_units WHERE name = 'داريا' AND level = 2)),
  -- حلب regions
  ('حلب القديمة', 3, (SELECT id FROM geo_units WHERE name = 'حلب القديمة' AND level = 2)),
  ('الجديدة', 3, (SELECT id FROM geo_units WHERE name = 'حلب القديمة' AND level = 2)),
  ('الشيخ فاضل', 3, (SELECT id FROM geo_units WHERE name = 'حلب القديمة' AND level = 2)),
  ('الشهباء', 3, (SELECT id FROM geo_units WHERE name = 'الشهباء' AND level = 2)),
  ('أرمان', 3, (SELECT id FROM geo_units WHERE name = 'الشهباء' AND level = 2)),
  ('صافيحان', 3, (SELECT id FROM geo_units WHERE name = 'الشهباء' AND level = 2)),
  ('أعزاز', 3, (SELECT id FROM geo_units WHERE name = 'أعزاز' AND level = 2)),
  ('باب حاتم', 3, (SELECT id FROM geo_units WHERE name = 'أعزاز' AND level = 2)),
  ('صانات', 3, (SELECT id FROM geo_units WHERE name = 'أعزاز' AND level = 2)),
  ('السفيرة', 3, (SELECT id FROM geo_units WHERE name = 'السفيرة' AND level = 2)),
  ('الخان العلوم', 3, (SELECT id FROM geo_units WHERE name = 'السفيرة' AND level = 2)),
  ('صيف الدولة', 3, (SELECT id FROM geo_units WHERE name = 'السفيرة' AND level = 2)),
  ('باب الفرج', 3, (SELECT id FROM geo_units WHERE name = 'باب الفرج' AND level = 2)),
  ('الفابرين', 3, (SELECT id FROM geo_units WHERE name = 'باب الفرج' AND level = 2)),
  ('الخصار', 3, (SELECT id FROM geo_units WHERE name = 'باب الفرج' AND level = 2)),
  ('النيرب', 3, (SELECT id FROM geo_units WHERE name = 'النيرب' AND level = 2)),
  ('العلي', 3, (SELECT id FROM geo_units WHERE name = 'النيرب' AND level = 2)),
  ('المحطة', 3, (SELECT id FROM geo_units WHERE name = 'النيرب' AND level = 2)),
  ('الأتارب', 3, (SELECT id FROM geo_units WHERE name = 'الأتارب' AND level = 2)),
  ('سبينة', 3, (SELECT id FROM geo_units WHERE name = 'الأتارب' AND level = 2)),
  ('الحداد', 3, (SELECT id FROM geo_units WHERE name = 'الأتارب' AND level = 2)),
  ('الحضر', 3, (SELECT id FROM geo_units WHERE name = 'الحضر' AND level = 2)),
  ('الحواش', 3, (SELECT id FROM geo_units WHERE name = 'الحضر' AND level = 2)),
  ('البوسرة', 3, (SELECT id FROM geo_units WHERE name = 'الحضر' AND level = 2)),
  -- اللاذقية regions
  ('اللاذقية', 3, (SELECT id FROM geo_units WHERE name = 'اللاذقية' AND level = 2)),
  ('سلنفة', 3, (SELECT id FROM geo_units WHERE name = 'اللاذقية' AND level = 2)),
  ('صيادة', 3, (SELECT id FROM geo_units WHERE name = 'اللاذقية' AND level = 2)),
  ('جبلة', 3, (SELECT id FROM geo_units WHERE name = 'جبلة' AND level = 2)),
  ('الربيعة', 3, (SELECT id FROM geo_units WHERE name = 'جبلة' AND level = 2)),
  ('بدروس', 3, (SELECT id FROM geo_units WHERE name = 'جبلة' AND level = 2)),
  ('القرداحة', 3, (SELECT id FROM geo_units WHERE name = 'القرداحة' AND level = 2)),
  ('قبر الشمس', 3, (SELECT id FROM geo_units WHERE name = 'القرداحة' AND level = 2)),
  ('حارة', 3, (SELECT id FROM geo_units WHERE name = 'القرداحة' AND level = 2)),
  ('الحفة', 3, (SELECT id FROM geo_units WHERE name = 'الحفة' AND level = 2)),
  ('بنس', 3, (SELECT id FROM geo_units WHERE name = 'الحفة' AND level = 2)),
  ('الجاندارية', 3, (SELECT id FROM geo_units WHERE name = 'الحفة' AND level = 2)),
  ('صلانفة', 3, (SELECT id FROM geo_units WHERE name = 'صلانفة' AND level = 2)),
  ('أرواد', 3, (SELECT id FROM geo_units WHERE name = 'صلانفة' AND level = 2)),
  ('القميشلي', 3, (SELECT id FROM geo_units WHERE name = 'صلانفة' AND level = 2)),
  -- حمص regions
  ('حمص القديمة', 3, (SELECT id FROM geo_units WHERE name = 'حمص القديمة' AND level = 2)),
  ('العداوية', 3, (SELECT id FROM geo_units WHERE name = 'حمص القديمة' AND level = 2)),
  ('باب تدمر', 3, (SELECT id FROM geo_units WHERE name = 'حمص القديمة' AND level = 2)),
  ('الواعر', 3, (SELECT id FROM geo_units WHERE name = 'الواعر' AND level = 2)),
  ('الدبل', 3, (SELECT id FROM geo_units WHERE name = 'الواعر' AND level = 2)),
  ('الجوشان', 3, (SELECT id FROM geo_units WHERE name = 'الواعر' AND level = 2)),
  ('المخرم', 3, (SELECT id FROM geo_units WHERE name = 'المخرم' AND level = 2)),
  ('المشرفة', 3, (SELECT id FROM geo_units WHERE name = 'المخرم' AND level = 2)),
  ('التالية', 3, (SELECT id FROM geo_units WHERE name = 'المخرم' AND level = 2)),
  ('القصير', 3, (SELECT id FROM geo_units WHERE name = 'القصير' AND level = 2)),
  ('السقلبية', 3, (SELECT id FROM geo_units WHERE name = 'القصير' AND level = 2)),
  ('شارعة فيصل', 3, (SELECT id FROM geo_units WHERE name = 'القصير' AND level = 2)),
  ('الرستن', 3, (SELECT id FROM geo_units WHERE name = 'الرستن' AND level = 2)),
  ('الترخايا', 3, (SELECT id FROM geo_units WHERE name = 'الرستن' AND level = 2)),
  ('عاليا', 3, (SELECT id FROM geo_units WHERE name = 'الرستن' AND level = 2)),
  ('تالدو', 3, (SELECT id FROM geo_units WHERE name = 'تالدو' AND level = 2)),
  ('شين', 3, (SELECT id FROM geo_units WHERE name = 'تالدو' AND level = 2)),
  ('العشارنة', 3, (SELECT id FROM geo_units WHERE name = 'تالدو' AND level = 2)),
  ('مصياف', 3, (SELECT id FROM geo_units WHERE name = 'مصياف' AND level = 2)),
  ('جورين', 3, (SELECT id FROM geo_units WHERE name = 'مصياف' AND level = 2)),
  ('ميراي', 3, (SELECT id FROM geo_units WHERE name = 'مصياف' AND level = 2)),
  ('المشتة', 3, (SELECT id FROM geo_units WHERE name = 'المشتة' AND level = 2)),
  ('الحسياء', 3, (SELECT id FROM geo_units WHERE name = 'المشتة' AND level = 2)),
  ('الفرقلس', 3, (SELECT id FROM geo_units WHERE name = 'المشتة' AND level = 2)),
  -- طرطوس regions
  ('طرطوس', 3, (SELECT id FROM geo_units WHERE name = 'طرطوس' AND level = 2)),
  ('البسيت', 3, (SELECT id FROM geo_units WHERE name = 'طرطوس' AND level = 2)),
  ('الريحانية', 3, (SELECT id FROM geo_units WHERE name = 'طرطوس' AND level = 2)),
  ('بنياس', 3, (SELECT id FROM geo_units WHERE name = 'بنياس' AND level = 2)),
  ('المنشية', 3, (SELECT id FROM geo_units WHERE name = 'بنياس' AND level = 2)),
  ('البادية', 3, (SELECT id FROM geo_units WHERE name = 'بنياس' AND level = 2)),
  ('الصافية', 3, (SELECT id FROM geo_units WHERE name = 'الصافية' AND level = 2)),
  ('الشيخ بدر', 3, (SELECT id FROM geo_units WHERE name = 'الصافية' AND level = 2)),
  ('العميقات', 3, (SELECT id FROM geo_units WHERE name = 'الصافية' AND level = 2)),
  ('الدريكيش', 3, (SELECT id FROM geo_units WHERE name = 'الدريكيش' AND level = 2)),
  ('البصاطة', 3, (SELECT id FROM geo_units WHERE name = 'الدريكيش' AND level = 2)),
  ('الربيضة', 3, (SELECT id FROM geo_units WHERE name = 'الدريكيش' AND level = 2)),
  ('شيخ بدر', 3, (SELECT id FROM geo_units WHERE name = 'شيخ بدر' AND level = 2)),
  ('بعيدة', 3, (SELECT id FROM geo_units WHERE name = 'شيخ بدر' AND level = 2)),
  ('الشيخ الساقط', 3, (SELECT id FROM geo_units WHERE name = 'شيخ بدر' AND level = 2))
ON CONFLICT DO NOTHING;

-- ============================================================
-- 3. NEIGHBORHOODS (الأحياء) — level 4
-- ============================================================
INSERT INTO geo_units (name, level, parent_id) VALUES
  -- دمشق القديمة sub-districts
  ('باب شرقي', 4, (SELECT id FROM geo_units WHERE name = 'الحميدية' AND level = 3)),
  ('المهاجرين', 4, (SELECT id FROM geo_units WHERE name = 'الحميدية' AND level = 3)),
  ('باب توما', 4, (SELECT id FROM geo_units WHERE name = 'الحميدية' AND level = 3)),
  ('سوق الحميدية', 4, (SELECT id FROM geo_units WHERE name = 'الحميدية' AND level = 3)),
  ('الشاغور', 4, (SELECT id FROM geo_units WHERE name = 'الصالحية' AND level = 3)),
  ('مسكن الصالحية', 4, (SELECT id FROM geo_units WHERE name = 'الصالحية' AND level = 3)),
  ('منطقة برامكه', 4, (SELECT id FROM geo_units WHERE name = 'الصالحية' AND level = 3)),
  ('المالكي', 4, (SELECT id FROM geo_units WHERE name = 'المالكي' AND level = 3)),
  ('شارع بركة', 4, (SELECT id FROM geo_units WHERE name = 'المالكي' AND level = 3)),
  ('جامع الأموي', 4, (SELECT id FROM geo_units WHERE name = 'المالكي' AND level = 3)),
  ('باب توما', 4, (SELECT id FROM geo_units WHERE name = 'باب توما' AND level = 3)),
  ('تل', 4, (SELECT id FROM geo_units WHERE name = 'باب توما' AND level = 3)),
  ('مزه', 4, (SELECT id FROM geo_units WHERE name = 'ميزه' AND level = 3)),
  ('الساحة', 4, (SELECT id FROM geo_units WHERE name = 'التل' AND level = 3)),
  ('جرمانا القديمة', 4, (SELECT id FROM geo_units WHERE name = 'جرمانا القديمة' AND level = 3)),
  ('عين الفيجة', 4, (SELECT id FROM geo_units WHERE name = 'جرمانا القديمة' AND level = 3)),
  ('بيت جند', 4, (SELECT id FROM geo_units WHERE name = 'بيت جند' AND level = 3)),
  ('محردة', 4, (SELECT id FROM geo_units WHERE name = 'محردة' AND level = 3)),
  ('المزة القديمة', 4, (SELECT id FROM geo_units WHERE name = 'مزة القديمة' AND level = 3)),
  ('المعرة', 4, (SELECT id FROM geo_units WHERE name = 'المعرة' AND level = 3)),
  ('بيت تمانة', 4, (SELECT id FROM geo_units WHERE name = 'بيت تمانة' AND level = 3)),
  ('دوما القديمة', 4, (SELECT id FROM geo_units WHERE name = 'دوما القديمة' AND level = 3)),
  ('المعرض', 4, (SELECT id FROM geo_units WHERE name = 'المعرض' AND level = 3)),
  ('بيت سادر', 4, (SELECT id FROM geo_units WHERE name = 'بيت سادر' AND level = 3)),
  -- القطيفة sub-districts
  ('القطيفة', 4, (SELECT id FROM geo_units WHERE name = 'القطيفة القديمة' AND level = 3)),
  ('العباسيين', 4, (SELECT id FROM geo_units WHERE name = 'العباسيين' AND level = 3)),
  ('كفر سوسة', 4, (SELECT id FROM geo_units WHERE name = 'كفر سوسة' AND level = 3)),
  -- المؤتمنة sub-districts
  ('المؤتمنة', 4, (SELECT id FROM geo_units WHERE name = 'المؤتمنة' AND level = 3)),
  ('جبادية', 4, (SELECT id FROM geo_units WHERE name = 'جبادية' AND level = 3)),
  ('الكفر', 4, (SELECT id FROM geo_units WHERE name = 'الكفر' AND level = 3)),
  -- داريا sub-districts
  ('داريا', 4, (SELECT id FROM geo_units WHERE name = 'داريا القديمة' AND level = 3)),
  ('الخليج', 4, (SELECT id FROM geo_units WHERE name = 'الخليج' AND level = 3)),
  ('بيت حجار', 4, (SELECT id FROM geo_units WHERE name = 'بيت حجار' AND level = 3)),
  -- حلب القديمة sub-districts
  ('حلب القديمة', 4, (SELECT id FROM geo_units WHERE name = 'حلب القديمة' AND level = 3)),
  ('الجديدة', 4, (SELECT id FROM geo_units WHERE name = 'الجديدة' AND level = 3)),
  ('الشيخ فاضل', 4, (SELECT id FROM geo_units WHERE name = 'الشيخ فاضل' AND level = 3)),
  ('الشهباء', 4, (SELECT id FROM geo_units WHERE name = 'الشهباء' AND level = 3)),
  ('أرمان', 4, (SELECT id FROM geo_units WHERE name = 'أرمان' AND level = 3)),
  ('صافيحان', 4, (SELECT id FROM geo_units WHERE name = 'صافيحان' AND level = 3)),
  ('أعزاز', 4, (SELECT id FROM geo_units WHERE name = 'أعزاز' AND level = 3)),
  ('باب حاتم', 4, (SELECT id FROM geo_units WHERE name = 'باب حاتم' AND level = 3)),
  ('صانات', 4, (SELECT id FROM geo_units WHERE name = 'صانات' AND level = 3)),
  ('السفيرة', 4, (SELECT id FROM geo_units WHERE name = 'السفيرة' AND level = 3)),
  ('الخان العلوم', 4, (SELECT id FROM geo_units WHERE name = 'الخان العلوم' AND level = 3)),
  ('صيف الدولة', 4, (SELECT id FROM geo_units WHERE name = 'صيف الدولة' AND level = 3)),
  ('باب الفرج', 4, (SELECT id FROM geo_units WHERE name = 'باب الفرج' AND level = 3)),
  ('الفابرين', 4, (SELECT id FROM geo_units WHERE name = 'الفابرين' AND level = 3)),
  ('الخصار', 4, (SELECT id FROM geo_units WHERE name = 'الخصار' AND level = 3)),
  ('النيرب', 4, (SELECT id FROM geo_units WHERE name = 'النيرب' AND level = 3)),
  ('العلي', 4, (SELECT id FROM geo_units WHERE name = 'العلي' AND level = 3)),
  ('المحطة', 4, (SELECT id FROM geo_units WHERE name = 'المحطة' AND level = 3)),
  ('الأتارب', 4, (SELECT id FROM geo_units WHERE name = 'الأتارب' AND level = 3)),
  ('سبينة', 4, (SELECT id FROM geo_units WHERE name = 'سبينة' AND level = 3)),
  ('الحداد', 4, (SELECT id FROM geo_units WHERE name = 'الحداد' AND level = 3)),
  ('الحضر', 4, (SELECT id FROM geo_units WHERE name = 'الحضر' AND level = 3)),
  ('الحواش', 4, (SELECT id FROM geo_units WHERE name = 'الحواش' AND level = 3)),
  ('البوسرة', 4, (SELECT id FROM geo_units WHERE name = 'البوسرة' AND level = 3)),
  -- اللاذقية sub-districts
  ('اللاذقية', 4, (SELECT id FROM geo_units WHERE name = 'اللاذقية' AND level = 3)),
  ('سلنفة', 4, (SELECT id FROM geo_units WHERE name = 'سلنفة' AND level = 3)),
  ('صيادة', 4, (SELECT id FROM geo_units WHERE name = 'صيادة' AND level = 3)),
  ('جبلة', 4, (SELECT id FROM geo_units WHERE name = 'جبلة' AND level = 3)),
  ('الربيعة', 4, (SELECT id FROM geo_units WHERE name = 'الربيعة' AND level = 3)),
  ('بدروس', 4, (SELECT id FROM geo_units WHERE name = 'بدروس' AND level = 3)),
  ('القرداحة', 4, (SELECT id FROM geo_units WHERE name = 'القرداحة' AND level = 3)),
  ('قبر الشمس', 4, (SELECT id FROM geo_units WHERE name = 'قبر الشمس' AND level = 3)),
  ('حارة', 4, (SELECT id FROM geo_units WHERE name = 'حارة' AND level = 3)),
  ('الحفة', 4, (SELECT id FROM geo_units WHERE name = 'الحفة' AND level = 3)),
  ('بنس', 4, (SELECT id FROM geo_units WHERE name = 'بنس' AND level = 3)),
  ('الجاندارية', 4, (SELECT id FROM geo_units WHERE name = 'الجاندارية' AND level = 3)),
  ('صلانفة', 4, (SELECT id FROM geo_units WHERE name = 'صلانفة' AND level = 3)),
  ('أرواد', 4, (SELECT id FROM geo_units WHERE name = 'أرواد' AND level = 3)),
  ('القميشلي', 4, (SELECT id FROM geo_units WHERE name = 'القميشلي' AND level = 3)),
  -- حمص sub-districts
  ('حمص القديمة', 4, (SELECT id FROM geo_units WHERE name = 'حمص القديمة' AND level = 3)),
  ('العداوية', 4, (SELECT id FROM geo_units WHERE name = 'العداوية' AND level = 3)),
  ('باب تدمر', 4, (SELECT id FROM geo_units WHERE name = 'باب تدمر' AND level = 3)),
  ('الواعر', 4, (SELECT id FROM geo_units WHERE name = 'الواعر' AND level = 3)),
  ('الدبل', 4, (SELECT id FROM geo_units WHERE name = 'الدبل' AND level = 3)),
  ('الجوشان', 4, (SELECT id FROM geo_units WHERE name = 'الجوشان' AND level = 3)),
  ('المخرم', 4, (SELECT id FROM geo_units WHERE name = 'المخرم' AND level = 3)),
  ('المشرفة', 4, (SELECT id FROM geo_units WHERE name = 'المشرفة' AND level = 3)),
  ('التالية', 4, (SELECT id FROM geo_units WHERE name = 'التالية' AND level = 3)),
  ('القصير', 4, (SELECT id FROM geo_units WHERE name = 'القصير' AND level = 3)),
  ('السقلبية', 4, (SELECT id FROM geo_units WHERE name = 'السقلبية' AND level = 3)),
  ('شارعة فيصل', 4, (SELECT id FROM geo_units WHERE name = 'شارعة فيصل' AND level = 3)),
  ('الرستن', 4, (SELECT id FROM geo_units WHERE name = 'الرستن' AND level = 3)),
  ('الترخايا', 4, (SELECT id FROM geo_units WHERE name = 'الترخايا' AND level = 3)),
  ('عاليا', 4, (SELECT id FROM geo_units WHERE name = 'عاليا' AND level = 3)),
  ('تالدو', 4, (SELECT id FROM geo_units WHERE name = 'تالدو' AND level = 3)),
  ('شين', 4, (SELECT id FROM geo_units WHERE name = 'شين' AND level = 3)),
  ('العشارنة', 4, (SELECT id FROM geo_units WHERE name = 'العشارنة' AND level = 3)),
  ('مصياف', 4, (SELECT id FROM geo_units WHERE name = 'مصياف' AND level = 3)),
  ('جورين', 4, (SELECT id FROM geo_units WHERE name = 'جورين' AND level = 3)),
  ('ميراي', 4, (SELECT id FROM geo_units WHERE name = 'ميراي' AND level = 3)),
  ('المشتة', 4, (SELECT id FROM geo_units WHERE name = 'المشتة' AND level = 3)),
  ('الحسياء', 4, (SELECT id FROM geo_units WHERE name = 'الحسياء' AND level = 3)),
  ('الفرقلس', 4, (SELECT id FROM geo_units WHERE name = 'الفرقلس' AND level = 3)),
  -- طرطوس sub-districts
  ('طرطوس', 4, (SELECT id FROM geo_units WHERE name = 'طرطوس' AND level = 3)),
  ('البسيت', 4, (SELECT id FROM geo_units WHERE name = 'البسيت' AND level = 3)),
  ('الريحانية', 4, (SELECT id FROM geo_units WHERE name = 'الريحانية' AND level = 3)),
  ('بنياس', 4, (SELECT id FROM geo_units WHERE name = 'بنياس' AND level = 3)),
  ('المنشية', 4, (SELECT id FROM geo_units WHERE name = 'المنشية' AND level = 3)),
  ('البادية', 4, (SELECT id FROM geo_units WHERE name = 'البادية' AND level = 3)),
  ('الصافية', 4, (SELECT id FROM geo_units WHERE name = 'الصافية' AND level = 3)),
  ('الشيخ بدر', 4, (SELECT id FROM geo_units WHERE name = 'الشيخ بدر' AND level = 3)),
  ('العميقات', 4, (SELECT id FROM geo_units WHERE name = 'العميقات' AND level = 3)),
  ('الدريكيش', 4, (SELECT id FROM geo_units WHERE name = 'الدريكيش' AND level = 3)),
  ('البصاطة', 4, (SELECT id FROM geo_units WHERE name = 'البصاطة' AND level = 3)),
  ('الربيضة', 4, (SELECT id FROM geo_units WHERE name = 'الربيضة' AND level = 3)),
  ('شيخ بدر', 4, (SELECT id FROM geo_units WHERE name = 'شيخ بدر' AND level = 3)),
  ('بعيدة', 4, (SELECT id FROM geo_units WHERE name = 'بعيدة' AND level = 3)),
  ('الشيخ الساقط', 4, (SELECT id FROM geo_units WHERE name = 'الشيخ الساقط' AND level = 3))
ON CONFLICT DO NOTHING;
