export const PERMISSION_MODULE_LABELS: Record<string, string> = {
  jobs: 'إدارة التوظيف',
  clients: 'سجلات الزبائن',
  candidates: 'الأسماء المقترحة',
  employees: 'سجلات الموظفين',
  contracts: 'العقود',
  devices: 'الأجهزة وقطع الغيار',
  tasks: 'المهام والعمليات',
  planning: 'تخطيط عمل الفرع',
  routes: 'خطوط السير وتوزيعها',
  catalog: 'كتالوج الأجهزة والأسعار',
  sales: 'المبيعات',
  telemarketer: 'إدارة المواعيد',
  geo: 'المناطق الجغرافية',
  branches: 'الفروع',
  settings: 'إعدادات النظام',
  admin: 'إدارة النظام والصلاحيات',
  users: 'المستخدمون',
  departments: 'الأقسام',
  marketing_visits: 'الزيارات التسويقية',
  telemarketing: 'التليماركتنغ',
  field_visits: 'الزيارات الميدانية',
  open_tasks: 'المهام المفتوحة',
  service_requests: 'طلبات الخدمة والصيانة',
  reference_data: 'القوائم المرجعية',
  water_check: 'طلبات فحص المياه',
  periodic_maintenance: 'طلبات الصيانة الدورية',
  golden_warranty: 'طلبات الكفالة الذهبية',
  name_nomination: 'طلبات ترشيح الأسماء',
  agent_license: 'طلبات ترخيص الوكلاء',
  account_requests: 'طلبات إنشاء الحساب',
  app_accounts: 'حسابات التطبيق',
  complaints: 'إدارة الشكاوى',
  reports: 'التقارير',
};

export const PERMISSION_SUBMODULE_LABELS: Record<string, string> = {
  vacancies: 'الشواغر الوظيفية',
  applications: 'طلبات التوظيف',
  interviews: 'المقابلات',
  training: 'الدورات التدريبية',
  candidates: 'الأسماء المقترحة',
  name_lists: 'لوائح الأسماء',
  roles: 'الأدوار والصلاحيات',
  roles_users: 'إسناد الأدوار للمستخدمين',
  system_lists: 'القوائم النظامية',
  users: 'المستخدمون',
  task_types: 'أنواع المهام',
  emergency_action_types: 'أنواع إجراءات الطوارئ',
  app_home_banners: 'بانرات الشاشة الرئيسية للتطبيق',
  app_contact_links: 'روابط التواصل الخاصة بالتطبيق',
  branch_assignments: 'فروع المستخدمين المسموحة',
  departments: 'أقسام الفروع',
  clients: 'بيانات الزبائن',
  profile_contacts: 'جهات الاتصال',
  profile_call_log: 'سجل الاتصالات',
  profile_visits: 'زيارات الزبون',
  profile_devices: 'أجهزة الزبون',
  profile_device_warranties: 'ضمانات الأجهزة',
  profile_purchase_history: 'سجل المشتريات',
  profile_parts_stock: 'مخزون قطع الغيار',
  profile_pre_offers: 'العروض الأولية',
  profile_network: 'شبكة العلاقات',
  profile_account_statement: 'كشف الحساب',
  profile_contact_control: 'التحكم بالتواصل',
  profile_rating: 'تقييم الزبون',
  assignment: 'إسناد المسؤولين',
  navigation: 'ظهور القسم',
  lookups: 'الاستخدام داخل العمليات',
  records: 'سجلات الموظفين',
  management: 'الإدارة',
  system: 'النظام',
  geography: 'المناطق الجغرافية',
  geo_units: 'الوحدات الجغرافية',
  visits: 'الزيارات',
  field_visits: 'إدارة الزيارات الميدانية',
  my_visits: 'زياراتي',
  create_instant: 'إنشاء زيارة فورية',
  tasks: 'المهام',
  periodic_maintenance: 'الصيانة الدورية',
  golden_warranty: 'الكفالة الذهبية',
  delivery: 'التسليم',
  installation: 'التركيب',
  demo: 'العرض التوضيحي',
  maintenance: 'الصيانة',
  collection: 'التحصيل',
  after_sales: 'ما بعد البيع',
  gifts: 'الهدايا',
  warranty: 'الضمان',
  activation: 'التفعيل',
  supervisor_alerts: 'تنبيهات المشرف',
  disconnection: 'قطع الخدمة',
  my_customers: 'زبائني',
  results: 'نتائج المهام',
  targets: 'الأهداف',
  lists: 'قوائم الاتصال',
  calls: 'المكالمات',
  appointments: 'المواعيد',
  schedule: 'جدولة الفرق',
  zone_study: 'دراسة المناطق',
  general: 'التخطيط العام',
  routes: 'خطوط السير',
  assignments: 'توزيع المسارات',
  service_requests: 'طلبات الخدمة والصيانة',
  water_check: 'فحص المياه',
  account_requests: 'طلبات إنشاء الحساب',
  app_accounts: 'حسابات التطبيق',
  device_models: 'تعريفات الأجهزة',
  spare_parts: 'تعريفات قطع الغيار',
  discounts: 'خصومات الأجهزة',
  department_availability: 'أجهزة الأقسام',
  installed_devices: 'الأجهزة المركبة',
  installed_device_possession: 'حيازة الأجهزة',
  prices: 'أسعار الأجهزة',
  spare_part_prices: 'أسعار قطع الغيار',
  devices: 'الأجهزة',
  contracts: 'العقود',
  complaints: 'سجلات الشكاوى',
  attachments: 'مرفقات الشكاوى',
  audit: 'سجل تدقيق الشكاوى',
  links: 'ربط الشكاوى بالسجلات',
  notes: 'الملاحظات الداخلية',
  reports: 'تقارير الشكاوى',
  settings: 'إعدادات الشكاوى',
  updates: 'التحديثات الظاهرة للمشتكي',
  workflow: 'دورة معالجة الشكوى',
  work_files: 'تقارير ملفات العمل',
  performance: 'تقارير الأداء',
  human_resources: 'تقارير الموارد البشرية',
  service: 'تقارير الخدمة',
  daily_work: 'تقارير العمل اليومي',
};

function readableIdentifier(identifier: string): string {
  return identifier
    .trim()
    .split(/[_\s.-]+/)
    .filter(Boolean)
    .join(' ');
}

export function getPermissionModuleLabel(module: string): string {
  return PERMISSION_MODULE_LABELS[module]
    ?? `قسم صلاحيات (${readableIdentifier(module) || 'غير مصنف'})`;
}

export function getPermissionSubmoduleLabel(subModule: string): string {
  return PERMISSION_SUBMODULE_LABELS[subModule]
    ?? `مجموعة صلاحيات (${readableIdentifier(subModule) || 'غير مصنفة'})`;
}
