import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowRight, Image as ImageIcon } from 'lucide-react';
import Button from '../../components/ui/Button';
import { usePermissions } from '../../hooks/usePermissions';
import { complaintsApi } from './complaintsApi';
import { COMPLAINT_CATEGORY_LABELS_AR } from '@golden-crm/shared';

const STATUS:Record<string,string>={new:'جديدة',triaged:'تم الفرز',assigned:'معيّنة',in_progress:'قيد المعالجة',awaiting_complainant:'بانتظار المشتكي',resolved:'محلولة',closed:'مغلقة',rejected:'مرفوضة',withdrawn:'مسحوبة'};
const TYPE:Record<string,string>={technical:'فنية',device:'جهاز',general:'عامة'};
const Card=({title,children}:{title:string;children:any})=><section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="mb-4 font-bold text-slate-900">{title}</h2>{children}</section>;
const Field=({label,value}:{label:string;value:any})=><div><div className="text-xs text-slate-500">{label}</div><div className="mt-1 text-sm text-slate-800">{value??'—'}</div></div>;

export default function ComplaintDetailPage(){
 const {id}=useParams();const {hasPermission}=usePermissions();const [data,setData]=useState<any>();const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const load=async()=>{try{setData(await complaintsApi.detail(id!));}catch(e){setError((e as Error).message);}};useEffect(()=>{void load();},[id]);
 const command=async(action:string,body:any={})=>{setBusy(true);setError('');try{await complaintsApi.command(id!,action,body);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 if(!data)return <div className="p-8 text-center">{error||'جار التحميل...'}</div>;
 const r=data.requester??{};
 return <div dir="rtl" className="p-6 space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><Link to="/complaints" className="mb-2 inline-flex items-center gap-1 text-sm text-sky-600"><ArrowRight className="h-4 w-4"/>قائمة الشكاوى</Link><h1 className="text-2xl font-bold">{data.public_ref_number}</h1><p className="text-sm text-slate-500">{TYPE[data.complaint_type]} · {new Date(data.created_at).toLocaleString('ar-SY')}</p></div><div className="flex items-center gap-2"><span className="rounded-full bg-sky-50 px-3 py-1.5 text-sky-700">{STATUS[data.status]??data.status}</span><span className="rounded-full bg-amber-50 px-3 py-1.5 text-amber-700">{data.priority}</span></div></div>
 {error&&<div className="rounded-lg bg-red-50 p-3 text-red-700">{error}</div>}
 <div className="grid gap-5 xl:grid-cols-[2fr_1fr]"><div className="space-y-5"><Card title="بيانات الشكوى"><div className="grid gap-4 md:grid-cols-3"><Field label="النوع" value={TYPE[data.complaint_type]}/><Field label="التصنيف" value={data.category_code==='other'?`أخرى${data.other_category_text?` — ${data.other_category_text}`:''}`:COMPLAINT_CATEGORY_LABELS_AR[data.category_code as keyof typeof COMPLAINT_CATEGORY_LABELS_AR]??'—'}/><Field label="المصدر" value={data.source_channel}/><Field label="نقطة الدخول" value={data.entry_point}/><Field label="فرع المعالجة" value={data.handling_branch_id}/><Field label="المعالج" value={data.assigned_user_id}/></div><div className="mt-5 rounded-lg bg-slate-50 p-4 whitespace-pre-wrap">{data.description}</div></Card>
 <Card title="مقدم الشكوى"><div className="grid gap-4 md:grid-cols-3"><Field label="الاسم" value={[r.first_name,r.middle_name,r.last_name].filter(Boolean).join(' ')}/><Field label="الهاتف الأساسي" value={r.primary_phone}/><Field label="واتساب" value={r.primary_phone_has_whatsapp==null?'غير محدد':r.primary_phone_has_whatsapp?'نعم':'لا'}/><Field label="الهاتف الثانوي" value={r.secondary_phone}/><Field label="المحافظة" value={r.address_snapshot?.governorate}/><Field label="العنوان التفصيلي" value={r.detailed_address}/></div></Card>
 {data.attachments?.length>0&&<Card title="صور الشكوى"><div className="flex flex-wrap gap-3">{data.attachments.map((a:any)=><button key={a.id} onClick={()=>void complaintsApi.openAttachment(id!,a.id).catch(e=>setError(e.message))} className="flex h-24 w-32 items-center justify-center rounded-lg border bg-slate-50 text-sky-600 hover:bg-sky-50"><ImageIcon/></button>)}</div></Card>}
 <Card title="التحديثات الظاهرة للمشتكي"><div className="space-y-3">{(data.publicUpdates??[]).map((x:any)=><div key={x.id} className="border-r-2 border-sky-400 pr-3"><div className="text-sm">{x.message}</div><div className="text-xs text-slate-400">{new Date(x.created_at).toLocaleString('ar-SY')}</div></div>)}</div>{hasPermission('complaints.publish_update')&&<Button className="mt-4" variant="secondary" onClick={()=>{const message=prompt('نص التحديث الظاهر للمشتكي');if(message)void command('public-updates',{message});}}>إضافة تحديث ظاهر</Button>}</Card>
 <Card title="الملاحظات الداخلية"><div className="space-y-2">{(data.internalNotes??[]).map((x:any)=><div key={x.id} className="rounded-lg bg-slate-50 p-3 text-sm">{x.note}</div>)}</div>{hasPermission('complaints.add_internal_note')&&<Button className="mt-4" variant="secondary" onClick={()=>{const note=prompt('الملاحظة الداخلية');if(note)void command('internal-notes',{note});}}>إضافة ملاحظة</Button>}</Card></div>
 <aside className="space-y-5"><Card title="إجراءات المعالجة"><div className="flex flex-col gap-2">{hasPermission('complaints.triage')&&data.status==='new'&&<Button disabled={busy} onClick={()=>void command('triage')}>فرز الشكوى</Button>}{hasPermission('complaints.assign_branch')&&!data.handling_branch_id&&<Button variant="secondary" onClick={()=>{const branchId=prompt('معرف فرع المعالجة');if(branchId)void command('assign-branch',{branchId:Number(branchId)});}}>تعيين فرع معالجة</Button>}{hasPermission('complaints.transfer_branch')&&data.handling_branch_id&&<Button variant="secondary" onClick={()=>{const branchId=prompt('معرف الفرع الجديد');if(branchId)void command('transfer-branch',{branchId:Number(branchId)});}}>نقل فرع المعالجة</Button>}{hasPermission('complaints.assign_handler')&&!data.assigned_user_id&&<Button variant="secondary" onClick={()=>{const userId=prompt('معرف المعالج');if(userId)void command('assign-handler',{userId:Number(userId)});}}>تعيين معالج</Button>}{hasPermission('complaints.reassign_handler')&&data.assigned_user_id&&<Button variant="secondary" onClick={()=>{const userId=prompt('معرف المعالج الجديد');if(userId)void command('reassign-handler',{userId:Number(userId)});}}>إعادة تعيين المعالج</Button>}{hasPermission('complaints.start_processing')&&data.status==='assigned'&&<Button onClick={()=>void command('start-processing')}>بدء المعالجة</Button>}{hasPermission('complaints.request_information')&&data.status==='in_progress'&&<Button variant="secondary" onClick={()=>void command('request-information')}>بانتظار معلومات المشتكي</Button>}{hasPermission('complaints.resume_processing')&&data.status==='awaiting_complainant'&&<Button onClick={()=>void command('resume-processing')}>استئناف المعالجة</Button>}{hasPermission('complaints.resolve')&&['in_progress','awaiting_complainant'].includes(data.status)&&<Button onClick={()=>{const outcome=prompt('النتيجة: upheld | partially_upheld | not_upheld | service_recovery_completed | redirected_to_service | duplicate_confirmed');const internalResolutionNotes=outcome&&prompt('ملاحظات الحل الداخلية');const publicResolutionSummary=internalResolutionNotes&&prompt('ملخص الحل الظاهر للمشتكي');if(publicResolutionSummary)void command('resolve',{outcome,internalResolutionNotes,publicResolutionSummary});}}>حل الشكوى</Button>}{hasPermission('complaints.close')&&data.status==='resolved'&&<Button onClick={()=>void command('close')}>إغلاق الشكوى</Button>}{hasPermission('complaints.reject')&&['new','triaged'].includes(data.status)&&<Button variant="danger" onClick={()=>void command('reject',{reason:prompt('سبب الرفض')})}>رفض الشكوى</Button>}{hasPermission('complaints.reopen')&&['resolved','closed','rejected','withdrawn'].includes(data.status)&&<Button variant="secondary" onClick={()=>void command('reopen',{reason:prompt('سبب إعادة الفتح')})}>إعادة فتح داخلياً</Button>}</div></Card>
 <Card title="سجل الحالة"><div className="space-y-3">{(data.statusHistory??[]).map((x:any)=><div key={x.id} className="text-sm"><b>{STATUS[x.to_status]??x.to_status}</b><div className="text-xs text-slate-400">{new Date(x.created_at).toLocaleString('ar-SY')}</div></div>)}</div></Card></aside></div></div>;
}
