import { FormEvent, useEffect, useMemo, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import GeoSmartSearch, { type GeoSelection } from '../../components/GeoSmartSearch';
import Button from '../../components/ui/Button';
import { api } from '../../lib/api';
import type { GeoUnit } from '../../lib/types';
import { complaintsApi } from './complaintsApi';
import {
  COMPLAINT_CATEGORY_LABELS_AR, DEVICE_COMPLAINT_CATEGORIES, TECHNICAL_COMPLAINT_CATEGORIES,
} from '@golden-crm/shared';

const inputClass='mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 focus:border-sky-400 focus:outline-none disabled:bg-slate-100';
const emptyGeo:GeoSelection={govId:'',regionId:'',subId:'',neighborhoodId:''};

function addressText(snapshot:any){const a=snapshot?.address;return a?[a.governorate,a.district,a.subArea,a.neighborhood,a.detailedAddress].filter(Boolean).join('، ')||'—':'—';}
function teamText(visit:any){return Object.values(visit?.team??{}).filter(Boolean).join('، ')||'الفريق غير موثق';}

export default function NewComplaintPage(){
  const navigate=useNavigate();const [params]=useSearchParams();
  const fixedDeviceId=params.get('deviceId');const fixedVisitId=params.get('visitId');const fixedContext=Boolean(fixedDeviceId||fixedVisitId);
  const [type,setType]=useState(fixedDeviceId?'device':fixedVisitId?'technical':'general');const [category,setCategory]=useState('');
  const [branches,setBranches]=useState<any[]>([]);const [branchId,setBranchId]=useState('');const [requesterMode,setRequesterMode]=useState<'linked'|'manual'>('linked');
  const [clients,setClients]=useState<any[]>([]);const [clientId,setClientId]=useState('');const [clientSnapshot,setClientSnapshot]=useState<any>(null);
  const [devices,setDevices]=useState<any[]>([]);const [visits,setVisits]=useState<any[]>([]);const [deviceMode,setDeviceMode]=useState<'installed'|'manual'>('installed');
  const [selectedDeviceId,setSelectedDeviceId]=useState(fixedDeviceId??'');const [selectedVisitId,setSelectedVisitId]=useState(fixedVisitId??'');
  const [geoUnits,setGeoUnits]=useState<GeoUnit[]>([]);const [geoSelection,setGeoSelection]=useState<GeoSelection>(emptyGeo);
  const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [lookupNotice,setLookupNotice]=useState('');

  useEffect(()=>{void (async()=>{setLoading(true);setError('');try{const b=await complaintsApi.createBranches();setBranches(b.items??[]);if(fixedContext){const r=await complaintsApi.context(fixedDeviceId?'device':'visit',(fixedDeviceId??fixedVisitId)!);setBranchId(String(r.record.branchId));setClientId(String(r.record.clientId));setClientSnapshot(r.clientSnapshot);setRequesterMode('linked');}}catch(e){setError((e as Error).message);}finally{setLoading(false);}})();},[fixedContext,fixedDeviceId,fixedVisitId]);

  useEffect(()=>{if(!branchId||fixedContext)return;setClientId('');setClientSnapshot(null);setDevices([]);setVisits([]);setSelectedDeviceId('');setSelectedVisitId('');setLookupNotice('');void complaintsApi.clientOptions(Number(branchId)).then(r=>setClients(r.items??[])).catch(()=>{setClients([]);setLookupNotice('لا تملك صلاحية عرض قائمة الزبائن في هذا الفرع.');});void api.geoUnits.list(Number(branchId)).then(setGeoUnits).catch(()=>setGeoUnits([]));},[branchId,fixedContext]);
  useEffect(()=>{if(!branchId||!clientId||fixedContext)return;setClientSnapshot(null);setDevices([]);setVisits([]);setSelectedDeviceId('');setSelectedVisitId('');setLookupNotice('');void complaintsApi.clientOption(Number(clientId),Number(branchId)).then(r=>setClientSnapshot(r.snapshot)).catch(e=>setError(e.message));},[branchId,clientId,fixedContext]);
  useEffect(()=>{if(!branchId||!clientId||fixedContext)return;setLookupNotice('');if(type==='device')void complaintsApi.clientDevices(Number(clientId),Number(branchId)).then(r=>{setDevices(r.items??[]);if(!(r.items??[]).length)setDeviceMode('manual');}).catch(()=>{setDevices([]);setDeviceMode('manual');setLookupNotice('لا تملك صلاحية عرض أجهزة هذا الزبون؛ يمكنك إدخال جهاز آخر يدويًا.');});if(type==='technical')void complaintsApi.clientVisits(Number(clientId),Number(branchId)).then(r=>setVisits(r.items??[])).catch(()=>{setVisits([]);setLookupNotice('لا تملك صلاحية عرض زيارات هذا الزبون؛ يمكنك إدخال الجهة المشكو عليها يدويًا.');});},[branchId,clientId,type,fixedContext]);
  useEffect(()=>{setCategory('');if(!fixedContext){setSelectedVisitId('');setSelectedDeviceId('');}},[type,fixedContext]);

  const selectedVisit=useMemo(()=>visits.find(v=>String(v.id)===selectedVisitId),[visits,selectedVisitId]);const selectedDevice=useMemo(()=>devices.find(v=>String(v.id)===selectedDeviceId),[devices,selectedDeviceId]);
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSaving(true);setError('');const form=new FormData(e.currentTarget);const value=(key:string)=>String(form.get(key)??'').trim();try{if(!branchId)throw new Error('يجب اختيار الفرع');if(requesterMode==='linked'&&!clientId)throw new Error('يجب اختيار الزبون أو التحويل إلى الإدخال اليدوي');if(requesterMode==='manual'&&!geoSelection.govId)throw new Error('يجب اختيار المحافظة من SmartGeo');const linkedDeviceId=type==='device'&&deviceMode==='installed'?selectedDeviceId:null;const visitId=type==='technical'?selectedVisitId:null;const payload:any={complaintType:type,categoryCode:type==='general'?null:category,otherCategoryText:category==='other'?value('otherCategoryText'):null,description:value('description'),sourceChannel:value('sourceChannel'),expectedContactMethod:value('expectedContactMethod'),originBranchId:Number(branchId),entryPoint:visitId?'crm_visit':linkedDeviceId?'crm_device':requesterMode==='linked'?'crm_client':'crm_general',requesterClientId:requesterMode==='linked'?Number(clientId):null,fieldVisitId:visitId?Number(visitId):null,installedDeviceId:linkedDeviceId?Number(linkedDeviceId):null,incidentDate:visitId?null:value('incidentDate')||null,reportedTargetName:visitId?null:value('reportedTargetName')||null,deviceName:type==='device'&&!linkedDeviceId?value('deviceName'):null,deviceSerialNumber:type==='device'&&!linkedDeviceId?value('deviceSerialNumber'):null,lastMaintenanceDate:type==='device'?value('lastMaintenanceDate')||null:null};if(requesterMode==='manual')payload.requester={firstName:value('firstName'),fatherName:value('fatherName')||null,lastName:value('lastName'),primaryPhone:value('primaryPhone'),primaryPhoneHasWhatsapp:form.get('primaryWhatsapp')==='on',secondaryPhone:value('secondaryPhone')||null,secondaryPhoneHasWhatsapp:value('secondaryPhone')?form.get('secondaryWhatsapp')==='on':null,governorateId:Number(geoSelection.govId),regionId:geoSelection.regionId?Number(geoSelection.regionId):null,subdistrictId:geoSelection.subId?Number(geoSelection.subId):null,neighborhoodId:geoSelection.neighborhoodId?Number(geoSelection.neighborhoodId):null,detailedAddress:value('detailedAddress')||null};const result=await complaintsApi.create(payload);navigate(`/complaints/${result.id}`);}catch(e){setError((e as Error).message);}finally{setSaving(false);}};

  if(loading)return <div className="p-8 text-center">جار تجهيز نموذج الشكوى...</div>;
  return <div dir="rtl" className="mx-auto max-w-6xl p-6"><div className="mb-5"><h1 className="text-2xl font-bold">تسجيل شكوى</h1><p className="text-sm text-slate-500">تسجيل داخلي مستقل عن الطلبات — لا يمكن للموظف إضافة مرفقات</p></div>{error&&<div className="mb-4 rounded-lg bg-red-50 p-3 text-red-700">{error}</div>}{lookupNotice&&<div className="mb-4 rounded-lg bg-amber-50 p-3 text-amber-800">{lookupNotice}</div>}<form onSubmit={submit} className="space-y-5">
    <section className="rounded-xl border bg-white p-5"><h2 className="mb-4 font-bold">الفرع ومقدم الشكوى</h2><div className="grid gap-4 md:grid-cols-2"><label>الفرع<select required value={branchId} disabled={fixedContext} onChange={e=>setBranchId(e.target.value)} className={inputClass}><option value="">اختر الفرع</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><div><div className="mb-2 text-sm">طريقة تحديد مقدم الشكوى</div><div className="flex gap-4 rounded-lg border p-2"><label><input type="radio" checked={requesterMode==='linked'} disabled={fixedContext} onChange={()=>setRequesterMode('linked')}/> زبون مسجل</label><label><input type="radio" checked={requesterMode==='manual'} disabled={fixedContext} onChange={()=>setRequesterMode('manual')}/> إدخال يدوي</label></div></div>{requesterMode==='linked'&&<label className="md:col-span-2">الزبون<select required value={clientId} disabled={!branchId||fixedContext} onChange={e=>setClientId(e.target.value)} className={inputClass}><option value="">اختر الزبون</option>{fixedContext&&clientSnapshot&&<option value={clientId}>{clientSnapshot.fullName||[clientSnapshot.firstName,clientSnapshot.fatherName,clientSnapshot.lastName].filter(Boolean).join(' ')} — {clientSnapshot.primaryMobile}</option>}{clients.map(c=><option key={c.id} value={c.id}>{c.name} — {c.mobile}</option>)}</select></label>}</div>{requesterMode==='linked'&&clientSnapshot&&<div className="mt-4 grid gap-3 rounded-lg bg-slate-50 p-4 text-sm md:grid-cols-3"><div><span className="text-slate-500">الاسم:</span> {clientSnapshot.fullName||[clientSnapshot.firstName,clientSnapshot.fatherName,clientSnapshot.lastName].filter(Boolean).join(' ')}</div><div><span className="text-slate-500">الهاتف:</span> {clientSnapshot.primaryMobile||'—'}</div><div><span className="text-slate-500">التصنيف:</span> {clientSnapshot.classification||'—'}</div><div className="md:col-span-3"><span className="text-slate-500">العنوان:</span> {addressText(clientSnapshot)}</div></div>}</section>
    {requesterMode==='manual'&&<><section className="rounded-xl border bg-white p-5"><h2 className="mb-4 font-bold">بيانات مقدم الشكوى</h2><div className="grid gap-4 md:grid-cols-3"><label>الاسم الأول<input required name="firstName" className={inputClass}/></label><label>اسم الأب (اختياري)<input name="fatherName" className={inputClass}/></label><label>الكنية<input required name="lastName" className={inputClass}/></label><label>الهاتف الأساسي<input required name="primaryPhone" className={inputClass}/></label><label className="flex items-end gap-2 pb-2"><input type="checkbox" name="primaryWhatsapp"/> يدعم واتساب</label><label>الهاتف الثانوي<input name="secondaryPhone" className={inputClass}/></label><label className="flex items-end gap-2 pb-2"><input type="checkbox" name="secondaryWhatsapp"/> الثانوي يدعم واتساب</label></div></section><section className="rounded-xl border bg-white p-5"><h2 className="mb-4 font-bold">العنوان</h2>{geoUnits.length?<GeoSmartSearch label="الموقع الإداري" required geoUnits={geoUnits} value={geoSelection} onChange={setGeoSelection} placeholder="ابحث باسم المحافظة أو المنطقة أو الناحية أو الحي..."/>:<div className="rounded-lg bg-amber-50 p-3 text-sm text-amber-800">اختر الفرع وتأكد من امتلاك صلاحية SmartGeo لعرض العناوين.</div>}<label className="mt-4 block">العنوان التفصيلي<input name="detailedAddress" className={inputClass}/></label></section></>}
    <section className="rounded-xl border bg-white p-5"><h2 className="mb-4 font-bold">بيانات الشكوى</h2><div className="grid gap-4 md:grid-cols-2"><label>النوع<select value={type} onChange={e=>setType(e.target.value)} disabled={fixedContext} className={inputClass}><option value="general">عامة</option><option value="technical">فنية</option><option value="device">جهاز</option></select></label><label>مصدر التقديم<select required name="sourceChannel" className={inputClass}><option value="phone">اتصال هاتفي</option><option value="website">موقع الويب</option><option value="whatsapp">واتساب</option><option value="in_person">حضور شخصي</option></select></label><label>طريقة المتابعة<select name="expectedContactMethod" className={inputClass}><option value="no_preference">لا تفضيل</option><option value="phone">هاتف</option><option value="whatsapp">واتساب</option><option value="sms">رسالة نصية</option></select></label>{type!=='general'&&<label>التصنيف<select required value={category} onChange={e=>setCategory(e.target.value)} className={inputClass}><option value="">اختر التصنيف</option>{(type==='technical'?TECHNICAL_COMPLAINT_CATEGORIES:DEVICE_COMPLAINT_CATEGORIES).map(code=><option key={code} value={code}>{COMPLAINT_CATEGORY_LABELS_AR[code]}</option>)}</select></label>}{category==='other'&&<label className="md:col-span-2">التصنيف الآخر<input required name="otherCategoryText" maxLength={300} className={inputClass}/></label>}
      {type==='technical'&&requesterMode==='linked'&&!fixedVisitId&&<label className="md:col-span-2">زيارة مرتبطة (اختياري)<select value={selectedVisitId} onChange={e=>setSelectedVisitId(e.target.value)} className={inputClass}><option value="">دون ربط زيارة — إدخال الجهة يدويًا</option>{visits.map(v=><option key={v.id} value={v.id}>{new Date(v.scheduledDate).toLocaleDateString('ar-SY')} — {v.visitType||'زيارة'} — {teamText(v)}</option>)}</select></label>}{type==='technical'&&selectedVisitId&&<div className="md:col-span-2 rounded-lg bg-sky-50 p-3 text-sm text-sky-800"><b>فريق الزيارة:</b> {fixedVisitId?'سيتم اشتقاق الفريق من سجل الزيارة':teamText(selectedVisit)}</div>}{type==='technical'&&!selectedVisitId&&<><label>تاريخ الواقعة<input type="date" name="incidentDate" className={inputClass}/></label><label>اسم الموظف أو الفريق<input name="reportedTargetName" className={inputClass}/></label></>}
      {type==='device'&&requesterMode==='linked'&&!fixedDeviceId&&<div className="md:col-span-2"><div className="mb-2 text-sm">الجهاز المشكو منه</div><div className="flex gap-4 rounded-lg border p-3"><label><input type="radio" checked={deviceMode==='installed'} disabled={!devices.length} onChange={()=>setDeviceMode('installed')}/> جهاز مسجل للزبون</label><label><input type="radio" checked={deviceMode==='manual'} onChange={()=>setDeviceMode('manual')}/> جهاز آخر</label></div></div>}{type==='device'&&requesterMode==='linked'&&deviceMode==='installed'&&!fixedDeviceId&&<label className="md:col-span-2">اختر الجهاز<select required value={selectedDeviceId} onChange={e=>setSelectedDeviceId(e.target.value)} className={inputClass}><option value="">اختر الجهاز</option>{devices.map(d=><option key={d.id} value={d.id}>{d.name} — {d.serialNumber||'دون رقم تسلسلي'}</option>)}</select></label>}{type==='device'&&selectedDeviceId&&<div className="md:col-span-2 rounded-lg bg-sky-50 p-3 text-sm text-sky-800"><b>الجهاز:</b> {fixedDeviceId?'سيتم اشتقاق بيانات الجهاز من سجله':`${selectedDevice?.name??''} — ${selectedDevice?.serialNumber??'دون رقم تسلسلي'}`}</div>}{type==='device'&&!selectedDeviceId&&<><label>اسم الجهاز<input required name="deviceName" className={inputClass}/></label><label>الرقم التسلسلي<input required name="deviceSerialNumber" className={inputClass}/></label><label>تاريخ آخر صيانة<input type="date" name="lastMaintenanceDate" className={inputClass}/></label></>}<label className="md:col-span-2">وصف الشكوى<textarea required minLength={20} maxLength={5000} rows={5} name="description" className={inputClass}/></label></div></section>
    <div className="flex gap-3"><Button type="submit" loading={saving}>حفظ الشكوى</Button><Button type="button" variant="secondary" onClick={()=>navigate('/complaints')}>إلغاء</Button></div></form></div>;
}
